"""
Run this on YOUR machine to test the real Gemini call end-to-end through Node C.

Before running:
1. Make sure GEMINI_API_KEY is set (export GEMINI_API_KEY="...")
2. This uses the realistic test data (the actual Café Coffee Day results we got
   from Foursquare earlier), so no Foursquare call is needed for this test.

Run with: python3 test_real_gemini_call.py
"""

import sys
sys.path.insert(0, "..")

from nodes.rank import rank_and_explain

USER_LOCATION = {"lat": 28.6139, "lng": 77.2090}

REALISTIC_CANDIDATES = [
    {"name": "Café Coffee Day", "address": "Janpath (Next To Sarvana Bhawan)",
     "lat": 28.626639961580253, "lng": 77.21928786545695, "rating": None, "review_count": None, "price_level": None},
    {"name": "Café Coffee Day", "address": "Janpath, New Delhi, Delhi",
     "lat": 28.62687063328005, "lng": 77.2197650541998, "rating": None, "review_count": None, "price_level": None},
    {"name": "Blue Tokai Coffee Roasters", "address": "Khan Market, New Delhi",
     "lat": 28.5992, "lng": 77.2260, "rating": None, "review_count": None, "price_level": None},
]

fake_state = {
    "candidate_venues": REALISTIC_CANDIDATES,
    "merged_constraints": {"location": USER_LOCATION, "vibe": "chill", "occasion": "casual"},
}

print("Calling rank_and_explain with the REAL Gemini API...\n")
result = rank_and_explain(fake_state)

print(f"Chosen venue: {result['chosen_venue']['name']}")
print(f"Distance: {result['chosen_venue']['distance_km']} km")
print(f"\nReasoning generated by Gemini:\n  {result['reasoning']}")
